import { redirect } from "next/navigation";
import { auth } from "../../../auth";
import "../globals.css"

export const metadata = {
  title: "LMS | ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  if (session)redirect("/")

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
