import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { auth } from "../../../../auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "LMS | ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  if (session?.user?.role !== "admin") {
    redirect("/");
  }

  return (
    <html lang="en">
      <body>
        <Tabs defaultValue="dashboard" className="w-full border">
          <TabsList className="w-full my-4">
            <TabsTrigger value="dashboard" className="text-1xl rounded-xl">
              <Link href="/admin/dashboard">Dashboard</Link>
            </TabsTrigger>
            <TabsTrigger value="batches" className="text-1xl rounded-xl">
              <Link href="/admin/batches">Batches</Link>
            </TabsTrigger>
            <TabsTrigger value="courses" className="text-1xl rounded-xl">
              <Link href="/admin/courses">Courses</Link>
            </TabsTrigger>
            <TabsTrigger value="students" className="text-1xl rounded-xl">
              <Link href="/admin/students">Students</Link>
            </TabsTrigger>
            <TabsTrigger value="trainers" className="text-1xl rounded-xl">
              <Link href="/admin/trainers">Trainers</Link>
            </TabsTrigger>
            <TabsTrigger value="addmissions" className="text-1xl rounded-xl">
              <Link href="/admin/addmissions">Admissions</Link>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="dashboard">{children}</TabsContent>
          <TabsContent value="batches">{children}</TabsContent>
          <TabsContent value="courses">{children}</TabsContent>
          <TabsContent value="students">{children}</TabsContent>
          <TabsContent value="trainers">{children}</TabsContent>
          <TabsContent value="addmissions">{children}</TabsContent>
        </Tabs>
      </body>
    </html>
  );
}
