import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { auth } from "../../../../auth";
import { redirect } from "next/navigation";



export const metadata = {
  title: "LMS | ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth()
  if (session?.user?.role != "admin"){
    redirect("/")
  }

  return (
    <html lang="en">
      <body>

        <Tabs defaultValue="dashboard" className="w-full border ">
          <TabsList className="w-full my-4">
            <Link href={"/admin/dashboard"}>
              <TabsTrigger value="dashboard" className="text-1xl rounded-xl ">Dashboard</TabsTrigger>
            </Link>
            <Link href={"/admin/batches"}>
              <TabsTrigger value="batches" className="text-1xl rounded-xl ">Batches</TabsTrigger>
            </Link>
            <Link href={"/admin/courses"}>
              <TabsTrigger value="courses" className="text-1xl rounded-xl ">Courses</TabsTrigger>
            </Link>
            <Link href={"/admin/students"}>
              <TabsTrigger value="students" className="text-1xl rounded-xl ">Students</TabsTrigger>
            </Link>
            <Link href={"/admin/trainers"}>
              <TabsTrigger value="trainers" className="text-1xl rounded-xl ">Trainers</TabsTrigger>
            </Link>
          </TabsList>

          <TabsContent value="dashboard">{children}</TabsContent>
          <TabsContent value="batches">{children}</TabsContent>
          <TabsContent value="courses">{children}</TabsContent>
          <TabsContent value="students">{children}</TabsContent>
          <TabsContent value="trainers">{children}</TabsContent>

        </Tabs>

      </body>
    </html>
  );
}
